# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"]\n\x13ProcessPhotoRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncreator_id\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x19\n\x11original_filename\x18\x04 \x01(\t\"5\n\x14ProcessPhotoResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"D\n\x15ProcessFacecamRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncreator_id\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\"7\n\x16ProcessFacecamResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"-\n\x0b\x41IBulkPhoto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\ncreator_id\x18\x02 \x01(\t\"`\n\x07\x41IPhoto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\x0e\x63ompressed_url\x18\x05 \x01(\t\x12\x16\n\x0e\x63ollection_url\x18\x06 \x01(\t\x12\x19\n\x11original_filename\x18\x07 \x01(\t\"d\n\x17ProcessBulkPhotoRequest\x12(\n\x0fprocess_bulk_ai\x18\x01 \x01(\x0b\x32\x0f.ai.AIBulkPhoto\x12\x1f\n\nprocess_ai\x18\x02 \x03(\x0b\x32\x0b.ai.AIPhoto\"9\n\x18ProcessBulkPhotoResponse\x12\x0e\n\x06status\x18\x01 \x01(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xe6\x01\n\tAiService\x12\x41\n\x0cProcessPhoto\x12\x17.ai.ProcessPhotoRequest\x1a\x18.ai.ProcessPhotoResponse\x12G\n\x0eProcessFacecam\x12\x19.ai.ProcessFacecamRequest\x1a\x1a.ai.ProcessFacecamResponse\x12M\n\x10ProcessBulkPhoto\x12\x1b.ai.ProcessBulkPhotoRequest\x1a\x1c.ai.ProcessBulkPhotoResponseB\x0eZ\x0c.pkg/ai;aipbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014.pkg/ai;aipb'
  _globals['_PROCESSPHOTOREQUEST']._serialized_start=16
  _globals['_PROCESSPHOTOREQUEST']._serialized_end=109
  _globals['_PROCESSPHOTORESPONSE']._serialized_start=111
  _globals['_PROCESSPHOTORESPONSE']._serialized_end=164
  _globals['_PROCESSFACECAMREQUEST']._serialized_start=166
  _globals['_PROCESSFACECAMREQUEST']._serialized_end=234
  _globals['_PROCESSFACECAMRESPONSE']._serialized_start=236
  _globals['_PROCESSFACECAMRESPONSE']._serialized_end=291
  _globals['_AIBULKPHOTO']._serialized_start=293
  _globals['_AIBULKPHOTO']._serialized_end=338
  _globals['_AIPHOTO']._serialized_start=340
  _globals['_AIPHOTO']._serialized_end=436
  _globals['_PROCESSBULKPHOTOREQUEST']._serialized_start=438
  _globals['_PROCESSBULKPHOTOREQUEST']._serialized_end=538
  _globals['_PROCESSBULKPHOTORESPONSE']._serialized_start=540
  _globals['_PROCESSBULKPHOTORESPONSE']._serialized_end=597
  _globals['_AISERVICE']._serialized_start=600
  _globals['_AISERVICE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
