# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPhoto = channel.unary_unary(
                '/ai.AiService/ProcessPhoto',
                request_serializer=ai__pb2.ProcessPhotoRequest.SerializeToString,
                response_deserializer=ai__pb2.ProcessPhotoResponse.FromString,
                _registered_method=True)
        self.ProcessFacecam = channel.unary_unary(
                '/ai.AiService/ProcessFacecam',
                request_serializer=ai__pb2.ProcessFacecamRequest.SerializeToString,
                response_deserializer=ai__pb2.ProcessFacecamResponse.FromString,
                _registered_method=True)
        self.ProcessBulkPhoto = channel.unary_unary(
                '/ai.AiService/ProcessBulkPhoto',
                request_serializer=ai__pb2.ProcessBulkPhotoRequest.SerializeToString,
                response_deserializer=ai__pb2.ProcessBulkPhotoResponse.FromString,
                _registered_method=True)


class AiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFacecam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessBulkPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPhoto,
                    request_deserializer=ai__pb2.ProcessPhotoRequest.FromString,
                    response_serializer=ai__pb2.ProcessPhotoResponse.SerializeToString,
            ),
            'ProcessFacecam': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFacecam,
                    request_deserializer=ai__pb2.ProcessFacecamRequest.FromString,
                    response_serializer=ai__pb2.ProcessFacecamResponse.SerializeToString,
            ),
            'ProcessBulkPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessBulkPhoto,
                    request_deserializer=ai__pb2.ProcessBulkPhotoRequest.FromString,
                    response_serializer=ai__pb2.ProcessBulkPhotoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/ProcessPhoto',
            ai__pb2.ProcessPhotoRequest.SerializeToString,
            ai__pb2.ProcessPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFacecam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/ProcessFacecam',
            ai__pb2.ProcessFacecamRequest.SerializeToString,
            ai__pb2.ProcessFacecamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessBulkPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AiService/ProcessBulkPhoto',
            ai__pb2.ProcessBulkPhotoRequest.SerializeToString,
            ai__pb2.ProcessBulkPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
