# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import photo_pb2 as photo__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in photo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhotoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdatePhotographerPhoto = channel.unary_unary(
                '/photo.PhotoService/UpdatePhotographerPhoto',
                request_serializer=photo__pb2.UpdatePhotographerPhotoRequest.SerializeToString,
                response_deserializer=photo__pb2.UpdatePhotographerPhotoResponse.FromString,
                _registered_method=True)
        self.UpdateFaceRecogPhoto = channel.unary_unary(
                '/photo.PhotoService/UpdateFaceRecogPhoto',
                request_serializer=photo__pb2.UpdateFaceRecogPhotoRequest.SerializeToString,
                response_deserializer=photo__pb2.UpdateFaceRecogPhotoResponse.FromString,
                _registered_method=True)
        self.CreatePhoto = channel.unary_unary(
                '/photo.PhotoService/CreatePhoto',
                request_serializer=photo__pb2.CreatePhotoRequest.SerializeToString,
                response_deserializer=photo__pb2.CreatePhotoResponse.FromString,
                _registered_method=True)
        self.CreateUserSimilarFacecam = channel.unary_unary(
                '/photo.PhotoService/CreateUserSimilarFacecam',
                request_serializer=photo__pb2.CreateUserSimilarFacecamRequest.SerializeToString,
                response_deserializer=photo__pb2.CreateUserSimilarFacecamResponse.FromString,
                _registered_method=True)
        self.CreateFacecam = channel.unary_unary(
                '/photo.PhotoService/CreateFacecam',
                request_serializer=photo__pb2.CreateFacecamRequest.SerializeToString,
                response_deserializer=photo__pb2.CreateFacecamResponse.FromString,
                _registered_method=True)
        self.UpdatePhotoDetail = channel.unary_unary(
                '/photo.PhotoService/UpdatePhotoDetail',
                request_serializer=photo__pb2.UpdatePhotoDetailRequest.SerializeToString,
                response_deserializer=photo__pb2.UpdatePhotoDetailResponse.FromString,
                _registered_method=True)
        self.CreateUserSimilar = channel.unary_unary(
                '/photo.PhotoService/CreateUserSimilar',
                request_serializer=photo__pb2.CreateUserSimilarPhotoRequest.SerializeToString,
                response_deserializer=photo__pb2.CreateUserSimilarPhotoResponse.FromString,
                _registered_method=True)
        self.CreateCreator = channel.unary_unary(
                '/photo.PhotoService/CreateCreator',
                request_serializer=photo__pb2.CreateCreatorRequest.SerializeToString,
                response_deserializer=photo__pb2.CreateCreatorResponse.FromString,
                _registered_method=True)
        self.GetCreator = channel.unary_unary(
                '/photo.PhotoService/GetCreator',
                request_serializer=photo__pb2.GetCreatorRequest.SerializeToString,
                response_deserializer=photo__pb2.GetCreatorResponse.FromString,
                _registered_method=True)
        self.CalculatePhotoPrice = channel.unary_unary(
                '/photo.PhotoService/CalculatePhotoPrice',
                request_serializer=photo__pb2.CalculatePhotoPriceRequest.SerializeToString,
                response_deserializer=photo__pb2.CalculatePhotoPriceResponse.FromString,
                _registered_method=True)
        self.OwnerOwnPhotos = channel.unary_unary(
                '/photo.PhotoService/OwnerOwnPhotos',
                request_serializer=photo__pb2.OwnerOwnPhotosRequest.SerializeToString,
                response_deserializer=photo__pb2.OwnerOwnPhotosResponse.FromString,
                _registered_method=True)
        self.CreateBulkPhoto = channel.unary_unary(
                '/photo.PhotoService/CreateBulkPhoto',
                request_serializer=photo__pb2.CreateBulkPhotoRequest.SerializeToString,
                response_deserializer=photo__pb2.CreateBulkPhotoResponse.FromString,
                _registered_method=True)
        self.CreateBulkUserSimilarPhotos = channel.unary_unary(
                '/photo.PhotoService/CreateBulkUserSimilarPhotos',
                request_serializer=photo__pb2.CreateBulkUserSimilarPhotoRequest.SerializeToString,
                response_deserializer=photo__pb2.CreateBulkUserSimilarPhotoResponse.FromString,
                _registered_method=True)


class PhotoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdatePhotographerPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFaceRecogPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserSimilarFacecam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFacecam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePhotoDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUserSimilar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCreator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCreator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculatePhotoPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OwnerOwnPhotos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBulkPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBulkUserSimilarPhotos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhotoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdatePhotographerPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePhotographerPhoto,
                    request_deserializer=photo__pb2.UpdatePhotographerPhotoRequest.FromString,
                    response_serializer=photo__pb2.UpdatePhotographerPhotoResponse.SerializeToString,
            ),
            'UpdateFaceRecogPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFaceRecogPhoto,
                    request_deserializer=photo__pb2.UpdateFaceRecogPhotoRequest.FromString,
                    response_serializer=photo__pb2.UpdateFaceRecogPhotoResponse.SerializeToString,
            ),
            'CreatePhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePhoto,
                    request_deserializer=photo__pb2.CreatePhotoRequest.FromString,
                    response_serializer=photo__pb2.CreatePhotoResponse.SerializeToString,
            ),
            'CreateUserSimilarFacecam': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserSimilarFacecam,
                    request_deserializer=photo__pb2.CreateUserSimilarFacecamRequest.FromString,
                    response_serializer=photo__pb2.CreateUserSimilarFacecamResponse.SerializeToString,
            ),
            'CreateFacecam': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFacecam,
                    request_deserializer=photo__pb2.CreateFacecamRequest.FromString,
                    response_serializer=photo__pb2.CreateFacecamResponse.SerializeToString,
            ),
            'UpdatePhotoDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePhotoDetail,
                    request_deserializer=photo__pb2.UpdatePhotoDetailRequest.FromString,
                    response_serializer=photo__pb2.UpdatePhotoDetailResponse.SerializeToString,
            ),
            'CreateUserSimilar': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUserSimilar,
                    request_deserializer=photo__pb2.CreateUserSimilarPhotoRequest.FromString,
                    response_serializer=photo__pb2.CreateUserSimilarPhotoResponse.SerializeToString,
            ),
            'CreateCreator': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCreator,
                    request_deserializer=photo__pb2.CreateCreatorRequest.FromString,
                    response_serializer=photo__pb2.CreateCreatorResponse.SerializeToString,
            ),
            'GetCreator': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCreator,
                    request_deserializer=photo__pb2.GetCreatorRequest.FromString,
                    response_serializer=photo__pb2.GetCreatorResponse.SerializeToString,
            ),
            'CalculatePhotoPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculatePhotoPrice,
                    request_deserializer=photo__pb2.CalculatePhotoPriceRequest.FromString,
                    response_serializer=photo__pb2.CalculatePhotoPriceResponse.SerializeToString,
            ),
            'OwnerOwnPhotos': grpc.unary_unary_rpc_method_handler(
                    servicer.OwnerOwnPhotos,
                    request_deserializer=photo__pb2.OwnerOwnPhotosRequest.FromString,
                    response_serializer=photo__pb2.OwnerOwnPhotosResponse.SerializeToString,
            ),
            'CreateBulkPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBulkPhoto,
                    request_deserializer=photo__pb2.CreateBulkPhotoRequest.FromString,
                    response_serializer=photo__pb2.CreateBulkPhotoResponse.SerializeToString,
            ),
            'CreateBulkUserSimilarPhotos': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBulkUserSimilarPhotos,
                    request_deserializer=photo__pb2.CreateBulkUserSimilarPhotoRequest.FromString,
                    response_serializer=photo__pb2.CreateBulkUserSimilarPhotoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'photo.PhotoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('photo.PhotoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhotoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdatePhotographerPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/UpdatePhotographerPhoto',
            photo__pb2.UpdatePhotographerPhotoRequest.SerializeToString,
            photo__pb2.UpdatePhotographerPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFaceRecogPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/UpdateFaceRecogPhoto',
            photo__pb2.UpdateFaceRecogPhotoRequest.SerializeToString,
            photo__pb2.UpdateFaceRecogPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/CreatePhoto',
            photo__pb2.CreatePhotoRequest.SerializeToString,
            photo__pb2.CreatePhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserSimilarFacecam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/CreateUserSimilarFacecam',
            photo__pb2.CreateUserSimilarFacecamRequest.SerializeToString,
            photo__pb2.CreateUserSimilarFacecamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFacecam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/CreateFacecam',
            photo__pb2.CreateFacecamRequest.SerializeToString,
            photo__pb2.CreateFacecamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePhotoDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/UpdatePhotoDetail',
            photo__pb2.UpdatePhotoDetailRequest.SerializeToString,
            photo__pb2.UpdatePhotoDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUserSimilar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/CreateUserSimilar',
            photo__pb2.CreateUserSimilarPhotoRequest.SerializeToString,
            photo__pb2.CreateUserSimilarPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCreator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/CreateCreator',
            photo__pb2.CreateCreatorRequest.SerializeToString,
            photo__pb2.CreateCreatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCreator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/GetCreator',
            photo__pb2.GetCreatorRequest.SerializeToString,
            photo__pb2.GetCreatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculatePhotoPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/CalculatePhotoPrice',
            photo__pb2.CalculatePhotoPriceRequest.SerializeToString,
            photo__pb2.CalculatePhotoPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OwnerOwnPhotos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/OwnerOwnPhotos',
            photo__pb2.OwnerOwnPhotosRequest.SerializeToString,
            photo__pb2.OwnerOwnPhotosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBulkPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/CreateBulkPhoto',
            photo__pb2.CreateBulkPhotoRequest.SerializeToString,
            photo__pb2.CreateBulkPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBulkUserSimilarPhotos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/photo.PhotoService/CreateBulkUserSimilarPhotos',
            photo__pb2.CreateBulkUserSimilarPhotoRequest.SerializeToString,
            photo__pb2.CreateBulkUserSimilarPhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
